version: '3'
services:
  app:
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
      shm_size: '7gb'
    shm_size: '7gb'
    working_dir: '/usr/src/app'
    volumes:
      - ./app:/usr/src/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
